const express = require('express');
const { createNote, getNotes, getNote, updateNote, deleteNote } = require('../controllers/notesController');
const { authenticate } = require('../middleware/auth');
const router = express.Router();
router.use(authenticate);
router.post('/', createNote);
router.get('/', getNotes);
router.get('/:id', getNote);
router.put('/:id', updateNote);
router.delete('/:id', deleteNote);
module.exports = router;
